# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = '1'

project 'Runner', {
  'Debug' => :debug,
  'Release' => :release,
  'Profile' => :profile,
}

def flutter_install_all_ios_pods(ios_application_path = nil)
  native_additions_path = File.join(ios_application_path, 'Flutter', 'flutter_export_environment.sh')
  return unless File.exist?(native_additions_path)

  # This is the standard way to include Flutter plugins in your Podfile.
  # It reads the plugins from the .flutter-plugins file.
  script_phase :name => 'Run Script', :script => 'bash "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build'
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'

      # For permission_handler
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_CAMERA=1',
        'PERMISSION_PHOTOS=1',
        'PERMISSION_NOTIFICATIONS=1',
        'PERMISSION_REMINDERS=0',
        'PERMISSION_CONTACTS=0',
        'PERMISSION_LOCATION=0',
        'PERMISSION_MICROPHONE=1',
        'PERMISSION_SPEECH_RECOGNITION=0',
        'PERMISSION_MEDIA_LIBRARY=0',
        'PERMISSION_SENSORS=0',
        'PERMISSION_BLUETOOTH=0',
        'PERMISSION_APP_TRACKING_TRANSPARENCY=0',
        'PERMISSION_CRITICAL_ALERTS=0'
      ]
    end
  end
end
