const SUPABASE_BUCKET_URL = "https://hcqaseovlciadogewnsw.supabase.co/storage/v1/object/public/materials";

function getPath(path) {
    const remotePath = path.replace('assets/', '');
    // Encode each segment separately to preserve slashes
    return `${SUPABASE_BUCKET_URL}/${remotePath.split('/').map(seg => encodeURIComponent(seg)).join('/')}`;
}

let COURSE_DATA = [
    {
        "title": "ECE 505",
        "subtitle": "COMPUTER AIDED DESIGN",
        "icon": "fa-solid fa-computer",
        "credits": 3,
        "semester": 1,
        "pdfs": [
            {"title": "Introduction to CAD Tool", "path": getPath("assets/1st Semester/ECE505/ECE 505 INTRODUCTION TO CAD TOOL.pdf")},
            {"title": "Transient Analysis", "path": getPath("assets/1st Semester/ECE505/transient analysis .pdf")},
            {"title": "RC Circuit - Matlab", "path": getPath("assets/1st Semester/ECE505/RC circuit - Transient analysis with Matlab.pdf")},
            {"title": "Step Response of RLC", "path": getPath("assets/1st Semester/ECE505/Step Response of an RLC Circuit.pdf")},
            {"title": "Math Modeling", "path": getPath("assets/1st Semester/ECE505/Mathematical-Modeling-of-Mechanical-and-Electrical-Systems.pdf")},
            {"title": "Electronics using Matlab", "path": getPath("assets/1st Semester/ECE505/Matlab - Electronics and Circuit Analysis using Matlab.pdf")},
            {"title": "Electric Circuits (5th Ed)", "path": getPath("assets/1st Semester/ECE505/Fundamentals_Of_Electric_Circuits-5th-Edition.PDF")}
        ],
        "videos": [
            {"title": "Introduction to Computer Aided Design", "thumbnail": "https://img.youtube.com/vi/mFasqK_t9k8/0.jpg", "url": "https://youtu.be/mFasqK_t9k8"},
            {"title": "Transient Analysis of RC Circuits", "thumbnail": "https://img.youtube.com/vi/pM3p8B_11I0/0.jpg", "url": "https://youtu.be/pM3p8B_11I0"},
            {"title": "Step Response of RLC Circuits", "thumbnail": "https://img.youtube.com/vi/G-T_YtA5pTM/0.jpg", "url": "https://youtu.be/G-T_YtA5pTM"},
            {"title": "Mathematical Modeling of Electrical Systems", "thumbnail": "https://img.youtube.com/vi/zD_E9Sle5uY/0.jpg", "url": "https://youtu.be/zD_E9Sle5uY"},
            {"title": "Matlab for Circuit Analysis", "thumbnail": "https://img.youtube.com/vi/kCAsGg_uU6Y/0.jpg", "url": "https://youtu.be/kCAsGg_uU6Y"},
            {"title": "RLC Circuit State Space Modeling", "thumbnail": "https://img.youtube.com/vi/6_NoxP_n0r0/0.jpg", "url": "https://youtu.be/6_NoxP_n0r0"}
        ],
        "pastQuestions": [{"title": "505 Past Question", "path": getPath("assets/1st Semester/ECE505/505 past question.pdf")}]
    },
    {
        "title": "ECE 517",
        "subtitle": "REAL TIME COMPUTING & CONTROL",
        "icon": "fa-solid fa-clock",
        "credits": 3,
        "semester": 1,
        "pdfs": [
            {"title": "Real Time Computing Intro", "path": getPath("assets/1st Semester/ECE517/Real time computing and programming - intro.pdf")},
            {"title": "Sensors and Actuators", "path": getPath("assets/1st Semester/ECE517/Real Time computing and programming - sensors.pdf")},
            {"title": "Microcontrollers", "path": getPath("assets/1st Semester/ECE517/Real Time computing and programming - microcontrollers.pdf")},
            {"title": "Assembly Language", "path": getPath("assets/1st Semester/ECE517/Assembly_Language Textbook.pdf")},
            {"title": "Dr. Tony's Material", "path": getPath("assets/1st Semester/ECE517/Dr_Tony_s_material.pdf")},
            {"title": "Simon's Note", "path": getPath("assets/1st Semester/ECE517/ECE517 (Simon_s note).pdf")}
        ],
        "videos": [
            {"title": "Introduction to Real-Time Systems", "thumbnail": "https://img.youtube.com/vi/7p7M_7X-6Is/0.jpg", "url": "https://youtu.be/7p7M_7X-6Is"},
            {"title": "RTOS: Task Scheduling & Priorities", "thumbnail": "https://img.youtube.com/vi/F321087yYy4/0.jpg", "url": "https://youtu.be/F321087yYy4"},
            {"title": "Microcontrollers Hardware Architecture", "thumbnail": "https://img.youtube.com/vi/vS_T0K2oB_k/0.jpg", "url": "https://youtu.be/vS_T0K2oB_k"},
            {"title": "Sensors and Actuators in Control Systems", "thumbnail": "https://img.youtube.com/vi/p6K8G3K7UeM/0.jpg", "url": "https://youtu.be/p6K8G3K7UeM"},
            {"title": "Assembly Language Programming for Embedded", "thumbnail": "https://img.youtube.com/vi/w9KCH_W9Trc/0.jpg", "url": "https://youtu.be/w9KCH_W9Trc"},
            {"title": "Interrupts and Timers in Microcontrollers", "thumbnail": "https://img.youtube.com/vi/uV9E8p_Gv_k/0.jpg", "url": "https://youtu.be/uV9E8p_Gv_k"}
        ],
        "pastQuestions": [
            {"title": "517 Past Question", "path": getPath("assets/1st Semester/ECE517/517 past question.pdf")},
            {"title": "PQ 17-18", "path": getPath("assets/1st Semester/ECE517/pqECE_517_17-18.jpg")}
        ]
    },
    {
        "title": "ECE 519",
        "subtitle": "SEMINAR",
        "icon": "fa-solid fa-person-chalkboard",
        "credits": 1,
        "semester": 1,
        "pdfs": [],
        "videos": [],
        "pastQuestions": []
    },
    {
        "title": "ECE 527",
        "subtitle": "SOLID STATE ELECTRONICS",
        "icon": "fa-solid fa-bolt",
        "credits": 3,
        "semester": 1,
        "pdfs": [
            {"title": "Semiconductor Fabrication", "path": getPath("assets/1st Semester/ECE527/ECE 527 LECTURE 2 semiconductor fibrication process [Compatibility Mode].pdf")},
            {"title": "BJT Fabrication", "path": getPath("assets/1st Semester/ECE527/ECE 527 LECTURES  3 BJT fibrication [Compatibility Mode].pdf")},
            {"title": "MOSFET Fabrication", "path": getPath("assets/1st Semester/ECE527/ECE 527 LECTURES  4 MOSFET  fibrication.ppt.pptx")},
            {"title": "IC Processes", "path": getPath("assets/1st Semester/ECE527/Basic Integrated Circuit Processes.pdf")},
            {"title": "SRAM and DRAM", "path": getPath("assets/1st Semester/ECE527/ECE_527_SRAM_and_DRAM_handout.pdf")},
            {"title": "Thyristor Handout", "path": getPath("assets/1st Semester/ECE527/Thyristor_handout.pdf")},
            {"title": "SSE Lecture Note", "path": getPath("assets/1st Semester/ECE527/Solid State Electronics Lecture Note(1).pdf")}
        ],
        "videos": [
            {"title": "Semiconductor Fabrication Process", "thumbnail": "https://img.youtube.com/vi/FmP9X-pM_lI/0.jpg", "url": "https://youtu.be/FmP9X-pM_lI"},
            {"title": "BJT Structure and Working", "thumbnail": "https://img.youtube.com/vi/9w00XzH8m7Q/0.jpg", "url": "https://youtu.be/9w00XzH8m7Q"},
            {"title": "MOSFET Fabrication Step-by-Step", "thumbnail": "https://img.youtube.com/vi/stM8dJBB87Q/0.jpg", "url": "https://youtu.be/stM8dJBB87Q"},
            {"title": "Thyristors (SCR) and Power Electronics", "thumbnail": "https://img.youtube.com/vi/0AgP-RzEfs0/0.jpg", "url": "https://youtu.be/0AgP-RzEfs0"},
            {"title": "SRAM vs DRAM: Architecture & Operation", "thumbnail": "https://img.youtube.com/vi/fUfR_C96uCc/0.jpg", "url": "https://youtu.be/fUfR_C96uCc"},
            {"title": "Photolithography in IC Fabrication", "thumbnail": "https://img.youtube.com/vi/0pA9pI_A54M/0.jpg", "url": "https://youtu.be/0pA9pI_A54M"}
        ],
        "pastQuestions": [
            {"title": "527 Past Question", "path": getPath("assets/1st Semester/ECE527/527 past question.pdf")},
            {"title": "PQ 16-17", "path": getPath("assets/1st Semester/ECE527/ECE_527_16-17.jpg")},
            {"title": "PQ 17-18", "path": getPath("assets/1st Semester/ECE527/ECE_527_17-18.jpg")}
        ]
    },
    {
        "title": "ECE 529",
        "subtitle": "SYSTEM PROGRAMMING",
        "icon": "fa-solid fa-terminal",
        "credits": 3,
        "semester": 1,
        "pdfs": [],
        "videos": [],
        "pastQuestions": []
    },
    {
        "title": "ECE 531",
        "subtitle": "WIRELESS COMMUNICATION & NETWORK APPLICATIONS",
        "icon": "fa-solid fa-wifi",
        "credits": 3,
        "semester": 1,
        "pdfs": [],
        "videos": [],
        "pastQuestions": []
    },
    {
        "title": "ECE 537",
        "subtitle": "DIGITAL SIGNAL PROCESSING",
        "icon": "fa-solid fa-wave-square",
        "credits": 3,
        "semester": 1,
        "pdfs": [
            {"title": "Introduction to DSP", "path": getPath("assets/pdfs/ECE 537 - Lect - Introduction-1.pdf")},
            {"title": "Discrete-Time Systems", "path": getPath("assets/1st Semester/ECE537/Handout - Discrete-Time Systems.pdf")},
            {"title": "DT Convolution", "path": getPath("assets/1st Semester/ECE537/DT Convolution.pdf")},
            {"title": "Z-Transform", "path": getPath("assets/1st Semester/ECE537/14_ZTransform(revised 10-15).pdf")},
            {"title": "DSP (Dr. Obinna Part)", "path": getPath("assets/1st Semester/ECE537/ECE 537 (DR OBINNA_S PART).pdf")},
            {"title": "DSP (Li Tan)", "path": getPath("assets/1st Semester/ECE537/Digital_Signal_Processing__LI_TAN.pdf")},
            {"title": "DSP Schaum Outline", "path": getPath("assets/1st Semester/ECE537/DSP Schaum Outline Series.pdf")}
        ],
        "videos": [
            {"title": "Intro to DSP: Sampling & Reconstruction", "thumbnail": "https://img.youtube.com/vi/6dF6K9R3B0U/0.jpg", "url": "https://youtu.be/6dF6K9R3B0U"},
            {"title": "The Z-Transform: Region of Convergence", "thumbnail": "https://img.youtube.com/vi/n5V4X7zS_0s/0.jpg", "url": "https://youtu.be/n5V4X7zS_0s"},
            {"title": "Discrete Time Convolution Tutorial", "thumbnail": "https://img.youtube.com/vi/8mS_A-k0wXg/0.jpg", "url": "https://youtu.be/8mS_A-k0wXg"},
            {"title": "Fast Fourier Transform (FFT) Algorithm", "thumbnail": "https://img.youtube.com/vi/h7apO7q16V0/0.jpg", "url": "https://youtu.be/h7apO7q16V0"},
            {"title": "Digital Filter Design: FIR vs IIR", "thumbnail": "https://img.youtube.com/vi/1_8-V6_D6Yk/0.jpg", "url": "https://youtu.be/1_8-V6_D6Yk"},
            {"title": "Nyquist-Shannon Sampling Theorem", "thumbnail": "https://img.youtube.com/vi/FcXZ27L0m60/0.jpg", "url": "https://youtu.be/FcXZ27L0m60"}
        ],
        "pastQuestions": []
    },
    {
        "title": "ECE 539",
        "subtitle": "COMPUTER ARCHITECTURE & ARCHITECTURE",
        "icon": "fa-solid fa-microchip",
        "credits": 3,
        "semester": 1,
        "pdfs": [],
        "videos": [],
        "pastQuestions": []
    },
    {
        "title": "ECE 541",
        "subtitle": "ARTIFICIAL INTELLIGENCE & ROBOTICS",
        "icon": "fa-solid fa-robot",
        "credits": 3,
        "semester": 1,
        "pdfs": [],
        "videos": [],
        "pastQuestions": []
    },
    {
        "title": "ECE 518",
        "subtitle": "PROJECT",
        "icon": "fa-solid fa-diagram-project",
        "credits": 6,
        "semester": 2,
        "pdfs": [],
        "videos": [],
        "pastQuestions": []
    },
    {
        "title": "ECE 538",
        "subtitle": "DATA COMMUNICATION NETWORK",
        "icon": "fa-solid fa-network-wired",
        "credits": 3,
        "semester": 2,
        "pdfs": [],
        "videos": [],
        "pastQuestions": []
    },
    {
        "title": "ECE 542",
        "subtitle": "DATABASE MANAGEMENT SYSTEMS",
        "icon": "fa-solid fa-database",
        "credits": 3,
        "semester": 2,
        "pdfs": [
            {"title": "DBMS Introduction", "path": getPath("assets/2nd Semester/ECE 542 DATABASE MANAGEMENT/DBMS_INTRO_Lec1.pdf")},
            {"title": "ER Model", "path": getPath("assets/2nd Semester/ECE 542 DATABASE MANAGEMENT/DBMS_ER_MODEL_Lec2 new.pdf")},
            {"title": "EER Model", "path": getPath("assets/2nd Semester/ECE 542 DATABASE MANAGEMENT/DBMS_EER_MODEL_Lec3.pdf")},
            {"title": "Oracle Database Handout", "path": getPath("assets/2nd Semester/ECE 542 DATABASE MANAGEMENT/Oracle_Database_handout.pdf")},
            {"title": "Database System Concepts", "path": getPath("assets/2nd Semester/ECE 542 DATABASE MANAGEMENT/epdf.pub_database-system-concepts.pdf")},
            {"title": "Modern Database Management", "path": getPath("assets/2nd Semester/ECE 542 DATABASE MANAGEMENT/Modern Database Management - 10th Edition.pdf")}
        ],
        "videos": [
            {"title": "DBMS Introduction Full Course", "thumbnail": "https://img.youtube.com/vi/3EJ6S8_D_S8/0.jpg", "url": "https://youtu.be/3EJ6S8_D_S8"},
            {"title": "Entity Relationship (ER) Diagramming", "thumbnail": "https://img.youtube.com/vi/QpdhBUYk7Kk/0.jpg", "url": "https://youtu.be/QpdhBUYk7Kk"},
            {"title": "SQL Join Operations & Queries", "thumbnail": "https://img.youtube.com/vi/HXV3zeQKqGY/0.jpg", "url": "https://youtu.be/HXV3zeQKqGY"},
            {"title": "Database Normalization (1NF, 2NF, 3NF)", "thumbnail": "https://img.youtube.com/vi/UrYLYV7WSHM/0.jpg", "url": "https://youtu.be/UrYLYV7WSHM"},
            {"title": "Relational Algebra and Calculus", "thumbnail": "https://img.youtube.com/vi/H_8_G_o9t_w/0.jpg", "url": "https://youtu.be/H_8_G_o9t_w"},
            {"title": "B-Tree Indexing and Hashing", "thumbnail": "https://img.youtube.com/vi/aZjYr87r1b8/0.jpg", "url": "https://youtu.be/aZjYr87r1b8"}
        ],
        "pastQuestions": [
            {"title": "PQ 17-18 A", "path": getPath("assets/2nd Semester/ECE 542 DATABASE MANAGEMENT/ECE_542_17-18_A.jpg")},
            {"title": "PQ 17-18 B", "path": getPath("assets/2nd Semester/ECE 542 DATABASE MANAGEMENT/ECE_542_17-18_B.jpg")}
        ]
    },
    {
        "title": "ECE 554",
        "subtitle": "SOFTWARE ENGINEERING",
        "icon": "fa-solid fa-code",
        "credits": 3,
        "semester": 2,
        "pdfs": [],
        "videos": [],
        "pastQuestions": []
    },
    {
        "title": "ELE 504",
        "subtitle": "NETWORK ANALYSIS & SYNTHESIS",
        "icon": "fa-solid fa-chart-line",
        "credits": 3,
        "semester": 2,
        "pdfs": [],
        "videos": [],
        "pastQuestions": []
    },
    {
        "title": "ELE 574",
        "subtitle": "CONTROL SYSTEM ENGINEERING",
        "icon": "fa-solid fa-gears",
        "credits": 3,
        "semester": 2,
        "pdfs": [
            {"title": "Control Systems", "path": getPath("assets/2nd Semester/ELE 574 CONTROL SYSTEM ENGINEERING/CONTROL SYSTEMS.pdf")},
            {"title": "ELE 574 CONTROL SYSTEM.pdf", "path": getPath("assets/2nd Semester/ELE 574 CONTROL SYSTEM ENGINEERING/ELE 574 CONTROL SYSTEM.pdf")}
        ],
        "videos": [
            {"title": "Introduction to Control Systems", "thumbnail": "https://img.youtube.com/vi/STQpA_L7Y-M/0.jpg", "url": "https://youtu.be/STQpA_L7Y-M"},
            {"title": "Root Locus Technique Explained", "thumbnail": "https://img.youtube.com/vi/CRvVDoXJjQD/0.jpg", "url": "https://youtu.be/CRvVDoXJjQD"},
            {"title": "PID Control Tuning and Design", "thumbnail": "https://img.youtube.com/vi/UR0hOmjaZ0o/0.jpg", "url": "https://youtu.be/UR0hOmjaZ0o"},
            {"title": "Stability: Routh-Hurwitz Criterion", "thumbnail": "https://img.youtube.com/vi/F-6rE_qP5Ww/0.jpg", "url": "https://youtu.be/F-6rE_qP5Ww"},
            {"title": "Frequency Response and Bode Plots", "thumbnail": "https://img.youtube.com/vi/_p-E66id5_o/0.jpg", "url": "https://youtu.be/_p-E66id5_o"},
            {"title": "State Space Representation Intro", "thumbnail": "https://img.youtube.com/vi/6f5S-2ZisB8/0.jpg", "url": "https://youtu.be/6f5S-2ZisB8"}
        ],
        "pastQuestions": []
    }
];

const TIMETABLE = {
    "Monday": [
        {"time": "9:00 AM - 11:00 AM", "course": "ECE 505", "location": "Hall A"},
        {"time": "11:00 AM - 1:00 PM", "course": "ECE 541", "location": "Hall A"},
        {"time": "1:00 PM - 3:00 PM", "course": "ECE 529", "location": "Hall C"}
    ],
    "Tuesday": [
        {"time": "9:00 AM - 11:00 AM", "course": "ECE 527", "location": "Lab 1"},
        {"time": "11:00 AM - 1:00 PM", "course": "ECE 517", "location": "Hall B"}
    ],
    "Wednesday": [
        {"time": "9:00 AM - 11:00 AM", "course": "ECE 531", "location": "Hall D"},
        {"time": "11:00 AM - 1:00 PM", "course": "ECE 505 (Lab)", "location": "Lab 2"}
    ],
    "Thursday": [
        {"time": "9:00 AM - 11:00 AM", "course": "ECE 539", "location": "Hall B"}
    ],
    "Friday": []
};

const STUDENT_DATA = [
    {"regNumber": "2022364001", "surname": "EGWU", "firstName": "DOMINION"},
    {"regNumber": "2022364002", "surname": "OKWUDILI", "firstName": "ONYINYE"},
    {"regNumber": "2022364003", "surname": "EZEIGWE", "firstName": "CHARLES-LEO"},
    {"regNumber": "2022364004", "surname": "EZE", "firstName": "IFEANYI"},
    {"regNumber": "2022364005", "surname": "OBI", "firstName": "UGOCHUKWU"},
    {"regNumber": "2022364006", "surname": "ONYEGBULE", "firstName": "CHIDERA"},
    {"regNumber": "2022364007", "surname": "OKEKE", "firstName": "JASON"},
    {"regNumber": "2022364008", "surname": "OFORNEJELU", "firstName": "PETER"},
    {"regNumber": "2022364009", "surname": "EZEONYE", "firstName": "EMMANUEL"},
    {"regNumber": "2022364010", "surname": "CHUKWUMA", "firstName": "CHIMDINDU"},
    {"regNumber": "2022364011", "surname": "EBONA", "firstName": "SOMKENECHUKWU"},
    {"regNumber": "2022364012", "surname": "ONWUKA", "firstName": "VICTOR"},
    {"regNumber": "2022364013", "surname": "EZENWERE", "firstName": "VICTOR"},
    {"regNumber": "2022364014", "surname": "ODDIH", "firstName": "EMMANUEL"},
    {"regNumber": "2022364015", "surname": "NZEAKA", "firstName": "CHIEDOZIE"},
    {"regNumber": "2022364016", "surname": "NWOFOR", "firstName": "KENECHUKWU"},
    {"regNumber": "2022364017", "surname": "ENWERE", "firstName": "FRANCIS"},
    {"regNumber": "2022364018", "surname": "OBIDIMMA", "firstName": "GODWIN"},
    {"regNumber": "2022364019", "surname": "CHINEDU-UZOR", "firstName": "EBUBECHUKWU"},
    {"regNumber": "2022364020", "surname": "NWOYE", "firstName": "IFEANYICHUKWU"},
    {"regNumber": "2022364021", "surname": "EZE-GOLDEN", "firstName": "IFENNA"},
    {"regNumber": "2022364022", "surname": "OSUJI", "firstName": "DANIELLA"},
    {"regNumber": "2022364023", "surname": "UKO", "firstName": "CHUKWUBUIKE"},
    {"regNumber": "2022364024", "surname": "OGUNMOLA", "firstName": "ISAIAH"},
    {"regNumber": "2022364025", "surname": "OKWUBUNKA", "firstName": "VICTORY"},
    {"regNumber": "2022364026", "surname": "OKOYE", "firstName": "CALEB"},
    {"regNumber": "2022364027", "surname": "UDEKWE", "firstName": "SOMTO"},
    {"regNumber": "2022364028", "surname": "OBI", "firstName": "CELINE"},
    {"regNumber": "2022364029", "surname": "ABAJUE", "firstName": "BENEDICT"},
    {"regNumber": "2022364030", "surname": "RICHMAN", "firstName": "FAVOUR"},
    {"regNumber": "2022364031", "surname": "ANEKE", "firstName": "CHIEDOZIE"},
    {"regNumber": "2022364032", "surname": "IKETAKU", "firstName": "EKENE"},
    {"regNumber": "2022364033", "surname": "UCHENDU", "firstName": "CHINEDU"},
    {"regNumber": "2022364034", "surname": "AMA", "firstName": "EXCEL"},
    {"regNumber": "2022364035", "surname": "EZEBUIRO", "firstName": "MARVELLOUS"},
    {"regNumber": "2022364036", "surname": "NWAGBO", "firstName": "FRANCIS"},
    {"regNumber": "2022364037", "surname": "OKAFOR", "firstName": "FRANKLYN"},
    {"regNumber": "2022364038", "surname": "NWAZOJIE", "firstName": "CHARLES"},
    {"regNumber": "2022364039", "surname": "LUCKY-EMAKPOR", "firstName": "FORTUNE"},
    {"regNumber": "2022364040", "surname": "JOHN", "firstName": "CHINEYE"},
    {"regNumber": "2022364041", "surname": "OBINECHE", "firstName": "OGOCHUKWU"},
    {"regNumber": "2022364042", "surname": "EZEUKWU", "firstName": "VICTOR"},
    {"regNumber": "2022364043", "surname": "OBIDI", "firstName": "CHIDUBEM"},
    {"regNumber": "2022364044", "surname": "NWAOGU", "firstName": "UGOCHUKWU"},
    {"regNumber": "2022364045", "surname": "NKEBUISI", "firstName": "ANTHONY"},
    {"regNumber": "2022364046", "surname": "OKECHUKWU", "firstName": "DANIEL"},
    {"regNumber": "2022364047", "surname": "OFFOR", "firstName": "PROSPER"},
    {"regNumber": "2022364048", "surname": "SIBEUDU", "firstName": "OLISAELOKA"},
    {"regNumber": "2022364049", "surname": "NDUKWE", "firstName": "CHIMEREMEZE"},
    {"regNumber": "2022364050", "surname": "NNAMANI", "firstName": "MICHAEL"},
    {"regNumber": "2022364051", "surname": "MMANEME", "firstName": "PASCHAL"},
    {"regNumber": "2022364052", "surname": "ANASOR", "firstName": "CORNELIUS"},
    {"regNumber": "2022364053", "surname": "CHUKWUEMEKA", "firstName": "FRANKLYN"},
    {"regNumber": "2022364054", "surname": "OKEKE", "firstName": "HILARY"},
    {"regNumber": "2022364055", "surname": "IFEANYICHUKWU", "firstName": "VICTORY"},
    {"regNumber": "2022364056", "surname": "OKWU", "firstName": "UGOCHUKWU"},
    {"regNumber": "2022364057", "surname": "CHUKWU-OKEREKE", "firstName": "CHIMAOBIM"},
    {"regNumber": "2022364058", "surname": "AKUNNA", "firstName": "VICTORY"},
    {"regNumber": "2022364059", "surname": "ONYEAHANKEYA", "firstName": "ANGELA"},
    {"regNumber": "2022364060", "surname": "BASIL", "firstName": "VICTOR"},
    {"regNumber": "2022364061", "surname": "JEREMIAH", "firstName": "JOHN"},
    {"regNumber": "2022364062", "surname": "ONWUBALILI", "firstName": "TOCHUKWU"},
    {"regNumber": "2022364063", "surname": "DIARUA", "firstName": "CHINEDU"},
    {"regNumber": "2022364064", "surname": "BENJAMIN", "firstName": "JOAN"},
    {"regNumber": "2022364065", "surname": "OKATTA", "firstName": "EKENEDILICHUKWU"},
    {"regNumber": "2022364066", "surname": "UCHE", "firstName": "AMARACHUKWU"},
    {"regNumber": "2022364067", "surname": "OLAJIDE", "firstName": "AKINREFON"},
    {"regNumber": "2022364068", "surname": "CHIGOZIE", "firstName": "CHINWENDU"},
    {"regNumber": "2022364069", "surname": "WAMUO", "firstName": "CHIEME"},
    {"regNumber": "2022364070", "surname": "ONYEJEKWE", "firstName": "CHIMAOBI"},
    {"regNumber": "2022364071", "surname": "ANIAGOLU", "firstName": "BRENDAN"},
    {"regNumber": "2022364072", "surname": "AKOGWU", "firstName": "DAVID"},
    {"regNumber": "2022364073", "surname": "AUGUSTINE", "firstName": "ANTHONY"},
    {"regNumber": "2022364074", "surname": "NWORU", "firstName": "CHINEMEREM"},
    {"regNumber": "2022364075", "surname": "IFEMA", "firstName": "CHIEMELIE"},
    {"regNumber": "2022364076", "surname": "EJIOFOR", "firstName": "MADUABUCHI"},
    {"regNumber": "2022364077", "surname": "NDIBE", "firstName": "DIVINE"},
    {"regNumber": "2022364078", "surname": "NWOKEDI", "firstName": "EBUBECHUKWU"},
    {"regNumber": "2022364079", "surname": "ORJIAKOR", "firstName": "SOMTOOCHUKWU"},
    {"regNumber": "2022364080", "surname": "FREEMAN", "firstName": "DANIEL"},
    {"regNumber": "2022364081", "surname": "OLUGU", "firstName": "JERUSALEM"},
    {"regNumber": "2022364082", "surname": "CHINWEZE", "firstName": "KOSARACHUKWU"},
    {"regNumber": "2022364083", "surname": "UMEAKUNNE", "firstName": "HENRY"},
    {"regNumber": "2022364084", "surname": "REGINALD", "firstName": "CHIKEZIE"},
    {"regNumber": "2022364085", "surname": "OKORIE", "firstName": "EMMANUEL"},
    {"regNumber": "2022364086", "surname": "EMERIBE", "firstName": "GODWIN"},
    {"regNumber": "2022364087", "surname": "NDUBUISI", "firstName": "HENRY"},
    {"regNumber": "2022364088", "surname": "CHIMEZIE", "firstName": "CHIDOZIE"},
    {"regNumber": "2022364089", "surname": "EKWEBELEM", "firstName": "SONIA"},
    {"regNumber": "2022364090", "surname": "NWUBA", "firstName": "AUSTIN"},
    {"regNumber": "2022364091", "surname": "UCHEFUNA", "firstName": "CHIBUIKEM"},
    {"regNumber": "2022364092", "surname": "MICHAEL", "firstName": "CHUKWUEMELIE"},
    {"regNumber": "2022364093", "surname": "EJIKEME", "firstName": "CHIDUBEM"},
    {"regNumber": "2022364094", "surname": "NWORIE", "firstName": "PAUL"},
    {"regNumber": "2022364095", "surname": "ENEKWEIZU", "firstName": "KINGSLEY "},
    {"regNumber": "2022364096", "surname": "EBEBE", "firstName": "VICTORY"},
    {"regNumber": "2022364097", "surname": "NWANGWU", "firstName": "EMMANUEL"},
    {"regNumber": "2022364098", "surname": "ENEANIOFU", "firstName": "GODSGIFT"},
    {"regNumber": "2022364099", "surname": "OKOYE", "firstName": "ONYINYECHUKWU"},
    {"regNumber": "2022364100", "surname": "OKOJI", "firstName": "CHISOM"},
    {"regNumber": "2022364101", "surname": "CHU-UMEOKOLO", "firstName": "CHUKWUJIOKE"},
    {"regNumber": "2022364102", "surname": "IKE-OKONKWO", "firstName": "ESTHER"},
    {"regNumber": "2022364103", "surname": "RAYMOND", "firstName": "DAVID"},
    {"regNumber": "2022364104", "surname": "ECHEFUDIKE", "firstName": "VICTOR"},
    {"regNumber": "2022364105", "surname": "NDUAGUBA", "firstName": "ENOCH"},
    {"regNumber": "2022364106", "surname": "EPHRAIM", "firstName": "KINGSLEY"},
    {"regNumber": "2022364107", "surname": "OTIABAR", "firstName": "HENRY"},
    {"regNumber": "2022364108", "surname": "IWU", "firstName": "NESOCHUKWU"},
    {"regNumber": "2022364109", "surname": "CHIOMA", "firstName": "NITA"},
    {"regNumber": "2022364110", "surname": "UGWU", "firstName": "ARINZECHUKWU"},
    {"regNumber": "2022364111", "surname": "STEPHEN", "firstName": "MICHAEL"},
    {"regNumber": "2022364112", "surname": "JULIUS", "firstName": "FRANKLIN"},
    {"regNumber": "2022364113", "surname": "MBAH", "firstName": "KENECHUKWU"},
    {"regNumber": "2022364114", "surname": "EZE", "firstName": "CLEMENTMARY"},
    {"regNumber": "2022364115", "surname": "UGWU", "firstName": "GIDEON"},
    {"regNumber": "2022364116", "surname": "OKECHUKWU", "firstName": "FRANCIS"},
    {"regNumber": "2022364117", "surname": "EDEANI", "firstName": "VICTORY"},
    {"regNumber": "2022364118", "surname": "CHIBUIKE", "firstName": "CHIDINMA"},
    {"regNumber": "2022364119", "surname": "IFEAJUNA", "firstName": "LAURA"},
    {"regNumber": "2022364120", "surname": "AGIM", "firstName": "KENNEDY"},
    {"regNumber": "2022364121", "surname": "OKOYE", "firstName": "CHIEMELIE"},
    {"regNumber": "2022364122", "surname": "CHUKWUMA", "firstName": "DANIEL"},
    {"regNumber": "2022364123", "surname": "NDIBE", "firstName": "EBUBECHUKWU"},
    {"regNumber": "2022364124", "surname": "CHUKWU", "firstName": "CHIBUIKE"},
    {"regNumber": "2022364125", "surname": "NWOSU", "firstName": "CHIBUIKEM"},
    {"regNumber": "2022364126", "surname": "NDUBUISI", "firstName": "CHIBUZO"},
    {"regNumber": "2022364127", "surname": "OGUGUA", "firstName": "PAUL"},
    {"regNumber": "2022364128", "surname": "IWUCHUKWU", "firstName": "DANIEL"},
    {"regNumber": "2022364129", "surname": "AZUKA", "firstName": "CHRISTIAN"},
    {"regNumber": "2022364130", "surname": "RAPHEAL", "firstName": "TOCHUKWU"},
    {"regNumber": "2022364131", "surname": "OKEKE", "firstName": "CHIDUBEM"},
    {"regNumber": "2022364132", "surname": "ONWURAH", "firstName": "KINGSLEY"},
    {"regNumber": "2022364133", "surname": "UDEFI", "firstName": "EMMANUEL"},
    {"regNumber": "2022364134", "surname": "OTTI", "firstName": "EMMANUEL"},
    {"regNumber": "2022364135", "surname": "EDUZOR", "firstName": "BILI"},
    {"regNumber": "2022364136", "surname": "NWAIWU", "firstName": "ORUEBUBECHUKWU"},
    {"regNumber": "2022364137", "surname": "ONWE", "firstName": "CHIDERA"},
    {"regNumber": "2022364139", "surname": "ENEJE", "firstName": "ANTHONY"},
    {"regNumber": "2022364140", "surname": "UDO-EZIKA", "firstName": "CHUKWUDUMEBI"},
    {"regNumber": "2022364142", "surname": "ONWUKA", "firstName": "JOVETT"},
    {"regNumber": "2022364143", "surname": "NWEKE", "firstName": "UCHENNA"},
    {"regNumber": "2022364144", "surname": "CHUKWUKA", "firstName": "JOSHUA"},
    {"regNumber": "2022364145", "surname": "EMEAGWALI", "firstName": "EBUBECHUKWU"},
    {"regNumber": "2022364146", "surname": "CHRISTOPHER", "firstName": "NKEM"},
    {"regNumber": "2022364147", "surname": "ETOLUE", "firstName": "HENRY"},
    {"regNumber": "2022364148", "surname": "JEJENIWA", "firstName": "WISDOM"},
    {"regNumber": "2022364149", "surname": "ARINZE", "firstName": "NEHEMIAH"},
    {"regNumber": "2022364150", "surname": "MODEBE", "firstName": "CHUKWUDI"},
    {"regNumber": "2022364151", "surname": "NNAEMENA", "firstName": "IFEANYI"},
    {"regNumber": "2022364152", "surname": "UGOCHUKWU", "firstName": "EMMANUEL"},
    {"regNumber": "2022364153", "surname": "OKOROCHA", "firstName": "CHUKWUBUIKE"},
    {"regNumber": "2022364154", "surname": "OGUMELUM", "firstName": "CHUKWUEMERIE"},
    {"regNumber": "2022364155", "surname": "PRECIOUS", "firstName": "UMUKORO"},
    {"regNumber": "2022364156", "surname": "UMEH", "firstName": "KIERIAN"},
    {"regNumber": "2022364157", "surname": "ONYEGBALU", "firstName": "CHUKA"},
    {"regNumber": "2022364158", "surname": "ONYEKA", "firstName": "COLLINS"},
    {"regNumber": "2022364159", "surname": "TASSIE", "firstName": "CHINEMEREM"},
    {"regNumber": "2022364160", "surname": "UDEZUKA", "firstName": "FORTUNE"},
    {"regNumber": "2022364161", "surname": "IKE", "firstName": "KOSISOCHUKWU"},
    {"regNumber": "2022364162", "surname": "OFOMATA", "firstName": "EBUBECHUKWU"},
    {"regNumber": "2022364163", "surname": "MBACHU", "firstName": "UGOCHUKWU"},
    {"regNumber": "2022364164", "surname": "EMMANUEL", "firstName": "SOMTOCHUKWU"},
    {"regNumber": "2022364165", "surname": "EJIMBE", "firstName": "SAINT"},
    {"regNumber": "2022364166", "surname": "IKE", "firstName": "HENRY"},
    {"regNumber": "2022364167", "surname": "BERTRAND", "firstName": "ROSESHARON"}
];
